---
title: "Graphics_ggplot2"
author: "Cheryl"
date: "3/12/2018"
output: html_document
---

```{r, echo = FALSE}
library(tidyverse)
library(ggthemes)
```

```{r}
mpg
```
```{r}
myplot <- ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point(alpha = 0.4) # scatter plot w transparent points (alpha) 
myplot 
```

```{r}
ggplot(mpg,aes(x = displ, y = hwy, color = class)) +
  geom_point()
```

Make a scatterplot of 'hwy' versus 'cty' with different size points representing each 'class' and different colors for each fuel type ('fl'
)
```{r}
ggplot(mpg,aes(x = hwy, y = cty, size = class, color = fl)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy))+
  geom_point(alpha = 0.4, color = "blue")
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  facet_wrap( ~ manufacturer, nrow = 5) + # subplot
  theme_bw()
```
```{r}
ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_boxplot()
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Relationship between engine size and highway mileage", 
         x = "Engine size (liters displaced)",
         y = "Highway Mileage (mpg)") +
  theme(text = element_text(size=15)) + 
  theme_bw()
```
```{r}
ggplot(mpg, aes(x = fl, fill = class)) +
  geom_bar() 

```